### PR TITLE
Add Network panel tab

### PR DESCRIPTION
**Pull request by juliandescottes**
Just a very basic table-like panel with a fixed header to show network requests with BiDi:

image

### CODE REVIEW

**Review by lutien — APPROVED** [review]
Looks nice! Thanks, Julian!

**Comment by whimboo** [comment]
@juliandescottes I assume we show *all* the received events here and not only `browsingContext.responseCompleted`? As such we show 3x that many events compared to the internal devtools network panel. Not sure if that was planned or not.

**Comment by juliandescottes** [comment]
> @juliandescottes I assume we show _all_ the received events here and not only `browsingContext.responseCompleted`? As such we show 3x that many events compared to the internal devtools network panel. Not sure if that was planned or not.

As said on Elements, that should not be the case. Maybe make sure you are not having devtools open at the same time in the target browser, we might be showing requests made on behalf of the devtools panel? 

Edit: Turns out the confusion was mostly about the fact that the client persists logs (both for the console and the network panel). We "could" clear on navigation, but that usually limits what you can do with the tool, so I think the current default makes sense.

**Comment by whimboo** [comment]
The difference to DevTools is actually that we do not clear the list by default when a new navigation starts. As such we are accumulating events across different navigations which I initially missed.

**Pull request merged**
